on: [pull_request]

jobs:
  detekt-check:
  name: Run detekt check
  runs-on: ubuntu-20.04

  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with: {java-version: 1.8}
    - name: Run detekt
      run: ./gradlew detekt

  ktlint-check:
  name: Run ktlint check
  runs-on: ubuntu-20.04

  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with: {java-version: 1.8}
    - name: Run ktlintCheck
      run: ./gradlew ktlintCheck

  andoid-lint-check:
  name: Run android lint check
  runs-on: ubuntu-20.04

  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with: {java-version: 1.8}
    - name: Run android lint
      run: ./gradlew lint

  Unit-test:
  name: Run unit tests on PR in main
  runs-on: ubuntu-20.04

  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with: {java-version: 1.8}
    - name: Run unit tests
      run: ./gradlew test
